version: '3.1'

services:
  web:
    build: ./wildfly
    container_name: jupa-app
    restart: always
    depends_on:
      - db
    ports:
      - 8088:8080
      - 9990:9990
    volumes:
      - ./wildfly/deployments:/opt/jboss/wildlfy/standalone/deployments
  db:
    image: mariadb:10.4
    container_name: jupa-db
    restart: always
    ports:
      - 13306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: jupa
      MYSQL_USER: jupa
      MYSQL_PASSWORD: jupa
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
      - ./maria-conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    container_name: jupa-adminer
    restart: always
    ports:
      - 18080:8080
