version: '3.1'

services:
  web:
    image: tomee:8-jre-7.0.4-webprofile
    container_name: jupa-app
    restart: always
    depends_on:
      - db
    ports:
      - 8088:8080
    volumes:
      - ./webapps:/usr/local/tomee/webapps
      - ./tomee-conf:/ust/local/tomee/conf
  db:
    image: mariadb:10.3
    container_name: jupa-db
    restart: always
    ports:
      - 13306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: jupa
      MYSQL_USER: jupa
      MYSQL_PASSWORD: jupa
    volumes:
      - ./init-data:/docker-entrypoint-initdb.d
      - ./maria-conf:/etc/mysql/conf.d

  adminer:
    image: adminer
    container_name: jupa-adminer
    restart: always
    ports:
      - 18080:8080
