CREATE TABLE FEDERATION
(
  ID        INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME      VARCHAR(100)        NOT NULL,
  DISPLAYID INTEGER             NOT NULL
);

INSERT INTO FEDERATION VALUES (1, 'Bremen', 1);
INSERT INTO FEDERATION VALUES (2, 'Hamburg', 2);
INSERT INTO FEDERATION VALUES (3, 'Schleswig-Holstein', 3);
INSERT INTO FEDERATION VALUES (4, 'Mecklenburg-Vorpommern', 4);
INSERT INTO FEDERATION VALUES (5, 'Nordrhein-Westfalen', 5);
INSERT INTO FEDERATION VALUES (6, 'Hessen', 6);
INSERT INTO FEDERATION VALUES (7, 'Sachsen-Anhalt', 7);
INSERT INTO FEDERATION VALUES (8, 'Thüringen', 8);
INSERT INTO FEDERATION VALUES (9, 'Brandenburg', 9);
INSERT INTO FEDERATION VALUES (10, 'Berlin', 10);
INSERT INTO FEDERATION VALUES (11, 'Sachsen', 11);
INSERT INTO FEDERATION VALUES (12, 'Rheinland-Pfalz', 12);
INSERT INTO FEDERATION VALUES (13, 'Saarland', 13);
INSERT INTO FEDERATION VALUES (14, 'Baden', 14);
INSERT INTO FEDERATION VALUES (15, 'Würtemberg', 15);
INSERT INTO FEDERATION VALUES (16, 'Bayern', 16);
INSERT INTO FEDERATION VALUES (17, 'Niedersachsen', 17);
