CREATE TABLE DISTRICT (
  ID            INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME          VARCHAR(100) NOT NULL,
  FEDERATION_ID INTEGER      NOT NULL,
  DISPLAYID     CHARACTER(4) NOT NULL,
  FOREIGN KEY (FEDERATION_ID) REFERENCES FEDERATION (ID)
);
