CREATE TABLE CLUB (
  ID          INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME        VARCHAR(100) NOT NULL,
  DISTRICT_ID INTEGER      NOT NULL,
  DISPLAYID   CHARACTER(7) NOT NULL,
  FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT (ID)
);
