CREATE TABLE USER (
  ID       INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  FORENAME VARCHAR(255) NOT NULL,
  SURNAME  VARCHAR(255) NOT NULL,
  EMAIL    VARCHAR(255) NOT NULL,
  BIRTHDAY DATE         NOT NULL
);
