CREATE TABLE ROLE (
  ID   INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE VARCHAR(100) NOT NULL
);

CREATE TABLE USER_ROLE (
  ID    	  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID	  INTEGER NOT NULL,
  ROLE_ID	  INTEGER NOT NULL,
  RELATEDCLUB_ID INTEGER NOT NULL,
  CONSTRAINT USER_TO_ROLE_USER_ID_FK	FOREIGN KEY (USER_ID)		REFERENCES USER (ID),
  CONSTRAINT USER_TO_ROLE_ROLE_ID_FK	FOREIGN KEY (ROLE_ID) 		REFERENCES ROLE (ID),
  CONSTRAINT USER_TO_ROLE_CLUB_ID_FK	FOREIGN KEY (RELATEDCLUB_ID)	REFERENCES CLUB (ID)
);

CREATE TABLE ROLE_FUNCTION (
  ID          INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE_ID     INTEGER NOT NULL,
  FUNCTION_ID INTEGER NOT NULL,
  CONSTRAINT ROLE_TO_FUNCTION_ROLE_ID_FK	FOREIGN KEY (ROLE_ID)	  REFERENCES ROLE (ID),
  CONSTRAINT ROLE_TO_FUNCTION_FUNCTION_ID_FK	FOREIGN KEY (FUNCTION_ID) REFERENCES `FUNCTION` (ID)
);
