CREATE TABLE ROLE (
  ID   INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE VARCHAR(100) NOT NULL
);

INSERT INTO ROLE (ID, ROLE) VALUES (1, 'Vereinsvertreter');
INSERT INTO ROLE (ID, ROLE) VALUES (2, 'Bezirksvertreter');
INSERT INTO ROLE (ID, ROLE) VALUES (3, 'Referent Lehrwesen');
INSERT INTO ROLE (ID, ROLE) VALUES (4, 'Geschäftsstelle');

CREATE TABLE USER_ROLE (
  ID    	  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID	  INTEGER NOT NULL,
  ROLE_ID	  INTEGER NOT NULL,
  RELATED_CLUB_ID INTEGER NOT NULL,
  CONSTRAINT USER_TO_ROLE_USER_ID_FK	FOREIGN KEY (USER_ID)		REFERENCES USER (ID),
  CONSTRAINT USER_TO_ROLE_ROLE_ID_FK	FOREIGN KEY (ROLE_ID) 		REFERENCES ROLE (ID),
  CONSTRAINT USER_TO_ROLE_CLUB_ID_FK	FOREIGN KEY (RELATED_CLUB_ID)	REFERENCES CLUB (ID)
);

CREATE TABLE ROLE_FUNCTION (
  ID          INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE_ID     INTEGER NOT NULL,
  FUNCTION_ID INTEGER NOT NULL,
  CONSTRAINT ROLE_TO_FUNCTION_ROLE_ID_FK	FOREIGN KEY (ROLE_ID)	  REFERENCES ROLE (ID),
  CONSTRAINT ROLE_TO_FUNCTION_FUNCTION_ID_FK	FOREIGN KEY (FUNCTION_ID) REFERENCES `FUNCTION` (ID)
);

INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (1, 1, 1);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (2, 2, 2);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (3, 2, 3);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (4, 3, 2);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (5, 3, 4);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (6, 4, 5);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (7, 4, 6);
INSERT INTO ROLE_FUNCTION (ID, ROLE_ID, FUNCTION_ID) VALUES (8, 4, 7);
