CREATE TABLE ROLE (
  ID   INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE VARCHAR(100) NOT NULL
);

INSERT INTO ROLE VALUES (1, 'Vereinsvertreter');
INSERT INTO ROLE VALUES (2, 'Bezirksvertreter');
INSERT INTO ROLE VALUES (3, 'Referent Lehrwesen');

CREATE TABLE USER_ROLE (
  ID      INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL,
  CONSTRAINT USER_TO_ROLE_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  CONSTRAINT USER_TO_ROLE_ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

CREATE TABLE ROLE_FUNCTION (
  ID          INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROLE_ID     INTEGER NOT NULL,
  FUNCTION_ID INTEGER NOT NULL,
  CONSTRAINT ROLE_TO_FUNCTION_ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID),
  CONSTRAINT ROLE_TO_FUNCTION_FUNCTION_ID_FK FOREIGN KEY (FUNCTION_ID) REFERENCES `FUNCTION` (ID)
);

INSERT INTO ROLE_FUNCTION VALUES (1, 1, 1);
INSERT INTO ROLE_FUNCTION VALUES (2, 2, 2);
INSERT INTO ROLE_FUNCTION VALUES (3, 2, 3);
INSERT INTO ROLE_FUNCTION VALUES (4, 3, 2);
INSERT INTO ROLE_FUNCTION VALUES (5, 3, 4);
