CREATE TABLE ANNOTATION (
  ID   INTEGER     NOT NULL PRIMARY KEY  AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL
);

INSERT INTO ANNOTATION VALUES (1, 'Teilnehmer');
INSERT INTO ANNOTATION VALUES (2, 'Referent');
INSERT INTO ANNOTATION VALUES (3, 'Vorstand');
