CREATE TABLE DISCIPLINE (
  ID   INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(25) NOT NULL
);

INSERT INTO DISCIPLINE VALUES (1, 'Ju-Jutsu');
INSERT INTO DISCIPLINE VALUES (2, 'Jiu-Jitsu');
INSERT INTO DISCIPLINE VALUES (3, 'Brazilian Jiu-Jitsu');
INSERT INTO DISCIPLINE VALUES (4, 'Hanbo-Jutsu');
