CREATE TABLE GRADING (
  ID            INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DISCIPLINE_ID INTEGER     NOT NULL,
  NAME          VARCHAR(25) NOT NULL,
  SORTORDER     INTEGER     NOT NULL,
  CONSTRAINT GRADING_DISCIPLINE_ID_FK FOREIGN KEY (DISCIPLINE_ID) REFERENCES DISCIPLINE (ID)
);

CREATE TABLE USER_GRADING (
  ID         INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID    INTEGER NOT NULL,
  GRADING_ID INTEGER NOT NULL,
  DATE       DATE    NOT NULL,
  CONSTRAINT USER_GRADING_FK FOREIGN KEY (GRADING_ID) REFERENCES GRADING (ID),
  CONSTRAINT USER_GRADING_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

INSERT INTO GRADING VALUES(1,1,'6.1 Kyu',1);
INSERT INTO GRADING VALUES(2,1,'6.2 Kyu',2);
INSERT INTO GRADING VALUES(3,1,'5. Kyu',3);
INSERT INTO GRADING VALUES(4,1,'5.1 Kyu',4);
INSERT INTO GRADING VALUES(5,1,'5.2 Kyu',5);
INSERT INTO GRADING VALUES(6,1,'4. Kyu',6);
INSERT INTO GRADING VALUES(7,1,'4.1 Kyu',7);
INSERT INTO GRADING VALUES(8,1,'3. Kyu',8);
INSERT INTO GRADING VALUES(9,1,'3.1 Kyu',9);
INSERT INTO GRADING VALUES(10,1,'2. Kyu',10);
INSERT INTO GRADING VALUES(11,1,'2.1 Kyu',11);
INSERT INTO GRADING VALUES(12,1,'1. Kyu',12);
INSERT INTO GRADING VALUES(13,1,'1. Dan',13);
INSERT INTO GRADING VALUES(14,1,'2. Dan',14);
INSERT INTO GRADING VALUES(15,1,'3. Dan',15);
INSERT INTO GRADING VALUES(16,1,'4. Dan',16);
INSERT INTO GRADING VALUES(17,1,'5. Dan',17);
INSERT INTO GRADING VALUES(18,1,'6. Dan',18);
INSERT INTO GRADING VALUES(19,1,'7. Dan',19);
INSERT INTO GRADING VALUES(20,1,'8. Dan',20);
INSERT INTO GRADING VALUES(21,1,'9. Dan',21);
INSERT INTO GRADING VALUES(22,1,'10. Dan',22);
INSERT INTO GRADING VALUES(23,2,'6.1 Kyu',1);
INSERT INTO GRADING VALUES(24,2,'5. Kyu',2);
INSERT INTO GRADING VALUES(25,2,'5.1 Kyu',3);
INSERT INTO GRADING VALUES(26,2,'4. Kyu',4);
INSERT INTO GRADING VALUES(27,2,'4.1 Kyu',5);
INSERT INTO GRADING VALUES(28,2,'3. Kyu',6);
INSERT INTO GRADING VALUES(29,2,'2. Kyu',7);
INSERT INTO GRADING VALUES(30,2,'1. Kyu',8);
INSERT INTO GRADING VALUES(31,2,'1. Dan',9);
INSERT INTO GRADING VALUES(32,2,'2. Dan',10);
INSERT INTO GRADING VALUES(33,2,'3. Dan',11);
INSERT INTO GRADING VALUES(34,2,'4. Dan',12);
INSERT INTO GRADING VALUES(35,2,'5. Dan',13);
INSERT INTO GRADING VALUES(36,2,'6. Dan',14);
INSERT INTO GRADING VALUES(37,2,'7. Dan',15);
INSERT INTO GRADING VALUES(38,2,'8. Dan',16);
INSERT INTO GRADING VALUES(39,2,'9. Dan',17);
INSERT INTO GRADING VALUES(40,2,'10. Dan',18);
INSERT INTO GRADING VALUES(41,3,'Grey',1);
INSERT INTO GRADING VALUES(42,3,'Yellow',2);
INSERT INTO GRADING VALUES(43,3,'Orange',3);
INSERT INTO GRADING VALUES(44,3,'Green',4);
INSERT INTO GRADING VALUES(45,3,'Blue',5);
INSERT INTO GRADING VALUES(46,3,'Purple',6);
INSERT INTO GRADING VALUES(47,3,'Black',7);
INSERT INTO GRADING VALUES(48,4,'6.1 Kyu',1);
INSERT INTO GRADING VALUES(49,4,'5. Kyu',2);
INSERT INTO GRADING VALUES(50,4,'5.1 Kyu',3);
INSERT INTO GRADING VALUES(51,4,'4. Kyu',4);
INSERT INTO GRADING VALUES(52,4,'3. Kyu',5);
INSERT INTO GRADING VALUES(53,4,'2. Kyu',6);
INSERT INTO GRADING VALUES(54,4,'1. Kyu',7);
INSERT INTO GRADING VALUES(55,4,'1. Dan',8);
INSERT INTO GRADING VALUES(56,4,'2. Dan',9);
