CREATE TABLE GRADING (
  ID            INTEGER     NOT NULL PRIMARY KEY AUTO_INCREMENT,
  DISCIPLINE_ID INTEGER     NOT NULL,
  NAME          VARCHAR(25) NOT NULL,
  SORTORDER     INTEGER     NOT NULL,
  CONSTRAINT GRADING_DISCIPLINE_ID_FK FOREIGN KEY (DISCIPLINE_ID) REFERENCES DISCIPLINE (ID)
);

CREATE TABLE USER_GRADING (
  ID         INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID    INTEGER NOT NULL,
  GRADING_ID INTEGER NOT NULL,
  DATE       DATE    NOT NULL,
  CONSTRAINT USER_GRADING_FK FOREIGN KEY (GRADING_ID) REFERENCES GRADING (ID),
  CONSTRAINT USER_GRADING_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
