INSERT INTO ROLE (ID, ROLE) VALUES (1, 'Vereinsvertreter');
INSERT INTO ROLE (ID, ROLE) VALUES (2, 'Bezirksvertreter');
INSERT INTO ROLE (ID, ROLE) VALUES (3, 'Referent Lehrwesen');
INSERT INTO ROLE (ID, ROLE) VALUES (4, 'Geschäftsstelle');

INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (1, 1);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (2, 2);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (2, 3);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (3, 2);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (3, 4);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (4, 5);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (4, 6);
INSERT INTO ROLE_FUNCTION (ROLE_ID, FUNCTION_ID) VALUES (4, 7);
