INSERT INTO DISCIPLINE VALUES (1, 'Ju-Jutsu');
INSERT INTO DISCIPLINE VALUES (2, 'Jiu-Jitsu');
INSERT INTO DISCIPLINE VALUES (3, 'Brazilian Jiu-Jitsu');
INSERT INTO DISCIPLINE VALUES (4, 'Hanbo-Jutsu');
