INSERT INTO USER_ROLE VALUES (1, 2, 1);
INSERT INTO USER_ROLE VALUES (2, 3, 1);
INSERT INTO USER_ROLE VALUES (3, 4, 1);
INSERT INTO USER_ROLE VALUES (4, 5, 1);
INSERT INTO USER_ROLE VALUES (5, 4, 2);
INSERT INTO USER_ROLE VALUES (6, 5, 3);
