INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (1, 2, 1, 2);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (2, 3, 1, 1);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (3, 4, 1, 3);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (4, 5, 1, 4);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (5, 4, 2, 3);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (6, 5, 3, 4);
INSERT INTO USER_ROLE (ID, USER_ID, ROLE_ID, RELATEDCLUB_ID) VALUES (7, 6, 4, 6);
