CREATE TABLE club (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 )           NOT NULL PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  district_id INTEGER      NOT NULL,
  displayid   INTEGER      NOT NULL,
  FOREIGN KEY (district_id) REFERENCES district (id)
);

INSERT INTO club ("NAME", "DISTRICT_ID", "DISPLAYID") VALUES ('TV 1875 Paderborn', 6, 1);
INSERT INTO club ("NAME", "DISTRICT_ID", "DISPLAYID") VALUES ('SG Erfstadt 1970 e.V.', 8, 1);