CREATE TABLE federation (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 )         NOT NULL PRIMARY KEY,
  name      VARCHAR(100) NOT NULL,
  displayid INTEGER
);

INSERT INTO federation VALUES (1, 'Bremen', 1);
INSERT INTO federation VALUES (2, 'Hamburg', 2);
INSERT INTO federation VALUES (3, 'Schleswig-Holstein', 3);
INSERT INTO federation VALUES (4, 'Mecklenburg-Vorpommern', 4);
INSERT INTO federation VALUES (5, 'Nordrhein-Westfalen', 5);
INSERT INTO federation VALUES (6, 'Hessen', 6);
INSERT INTO federation VALUES (7, 'Sachsen-Anhalt', 7);
INSERT INTO federation VALUES (8, 'Thüringen', 8);
INSERT INTO federation VALUES (9, 'Brandenburg', 9);
INSERT INTO federation VALUES (10, 'Berlin', 10);
INSERT INTO federation VALUES (11, 'Sachsen', 11);
INSERT INTO federation VALUES (12, 'Rheinland-Pfalz', 12);
INSERT INTO federation VALUES (13, 'Saarland', 13);
INSERT INTO federation VALUES (14, 'Baden', 14);
INSERT INTO federation VALUES (15, 'Würtemberg', 15);
INSERT INTO federation VALUES (16, 'Bayern', 16);
INSERT INTO federation VALUES (17, 'Niedersachsen', 17);
