CREATE TABLE federation (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

INSERT INTO federation (name) VALUES ('Niedersachsen');
INSERT INTO federation (name) VALUES ('Bremen');
INSERT INTO federation (name) VALUES ('Hamburg');
INSERT INTO federation (name) VALUES ('Schleswig-Holstein');
INSERT INTO federation (name) VALUES ('Mecklenburg-Vorpommern');
INSERT INTO federation (name) VALUES ('Nordrhein-Westfalen');
INSERT INTO federation (name) VALUES ('Hessen');
INSERT INTO federation (name) VALUES ('Sachsen-Anhalt');
INSERT INTO federation (name) VALUES ('Thüringen');
INSERT INTO federation (name) VALUES ('Brandenburg');
INSERT INTO federation (name) VALUES ('Berlin');
INSERT INTO federation (name) VALUES ('Sachsen');
INSERT INTO federation (name) VALUES ('Rheinland-Pfalz');
INSERT INTO federation (name) VALUES ('Saarland');
INSERT INTO federation (name) VALUES ('Baden');
INSERT INTO federation (name) VALUES ('Würtemberg');
INSERT INTO federation (name) VALUES ('Bayern');

ALTER TABLE user
  ADD COLUMN federation_id INTEGER;

ALTER TABLE user
  ADD FOREIGN KEY (federation_id)
REFERENCES federation (id);