DROP TABLE user_roles;

CREATE TABLE user_roles (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  role     VARCHAR(255) NOT NULL
);

CREATE INDEX user_roles_username_idx
  ON user_roles (username);

INSERT INTO user_roles (username, role) VALUES ('admin', 'loginUser');
INSERT INTO user_roles (username, role) VALUES ('admin', 'useradmin');
