DROP TABLE user_roles;

CREATE TABLE user_roles (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  role     VARCHAR(255) NOT NULL
);

INSERT INTO user_roles (username, role) VALUES ('admin', 'superadmin');
INSERT INTO user_roles (username, role) VALUES ('0502001000022', 'club_chief');
INSERT INTO user_roles (username, role) VALUES ('0504001000019', 'club_chief');

