DROP TABLE user;

CREATE TABLE user (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  forename VARCHAR(255) NOT NULL,
  surname  VARCHAR(255) NOT NULL,
  club_id  INTEGER      NOT NULL,
  FOREIGN KEY (club_id) REFERENCES club (id)
);

INSERT INTO user (username, password, forename, surname, club_id) VALUES ('admin', 'admin', 'Super', 'Admin', 1);

INSERT INTO user (username, password, forename, surname, club_id)
VALUES ('0502001000015', 'falk', 'Falk', 'Harnisch', 1);
INSERT INTO user (username, password, forename, surname, club_id)
VALUES ('0502001000022', 'juergen', 'Jürgen', 'Thieke', 1);
INSERT INTO user (username, password, forename, surname, club_id) VALUES ('0504001000019', 'maike', 'Maike', 'John', 2);