DROP TABLE user;

CREATE TABLE user (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  forename VARCHAR(255),
  surname  VARCHAR(255)
);

INSERT INTO user
(username, password, forename, surname)
VALUES
  ('admin', 'admin', 'Super', 'Admin');
